---

- hosts: all
  become: yes
  tasks:
  
  - name: Install Apache2 App
    apt:
      name: apache2
  
  - name: 
###########################################
## RUN: ansible all -m ping -i inventory ##
###########################################

########################################################################
## RUN: ansible all --key-file ~/.ssh/ansible_id -m ping -i inventory ##
########################################################################
