---

- hosts: all
  become: yes
  tasks:
  
  - name: Update Repository Index
    apt:
      update_cache: yes

  - name: Remove Apache2 App
    apt:
      name: apache2
      state: absent #This will REMOVE the Apache APP

  - name: Add PhP Support for Apache
    apt:
      name: libapache2-mod-php
      state: latest  # This will ensure that the php support has the LATEST-UPDATE

###########################################
## RUN: ansible all -m ping -i inventory ##
###########################################

########################################################################
## RUN: ansible all --key-file ~/.ssh/ansible_id -m ping -i inventory ##
########################################################################
