---

- hosts: all
  become: yes
  tasks:

  - name: Install Updates [Ubuntu]
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  
  - name: Install Updates [CentOS]
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache2 App & PhP Support for Ubuntu
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install httpd Server & PhP for CentOS
    yum:
      name:
      - httpd
      - php
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_server
  become: true
  tasks:

  - name: Install MariaDB for Ubuntu
    apt:
      name:
      - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install MariaDB for CentOS
    yum:
      name:
      - mariadb
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: file_server
  become: true
  tasks:

  - name: Install Samba for Ubuntu
    package:
      name:
      - samba
      state: latest
    when: ansible_distribution == "Ubuntu"
