- name: Install MariaDB for Ubuntu
  tags: db, mariadb, ubuntu
  apt:
    name:
    - mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install MariaDB for CentOS
  tags: db, mariadb, centos
  yum:
    name:
    - mariadb
    state: latest
  when: ansible_distribution == "CentOS"
