- name: Install Unzip
  package:
    name: unzip

- name: Install Terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root
    mode: 0755
